### ISSUE TITLE
Cat behavior scale not working

### ISSUE THREAD

**Issue by freezecode** [JKesslerPhD/FIPInjectionLogger#44]
Using an iPhone 10, if I click the Cat Behavior 1-5 scale it all turns green, unclear what number I selected. When I review the Treatment Log, it usually shows that I selected 3. However, I try to click 5. Thanks!

**Comment by JKesslerPhD** [comment]
I should be able to get this problem fixed later tonight.  It looks like it's a Safari issue when using iOS (I've been primarily testing on Android, so missed this issue).  In the meantime, if you use Safari on a computer, or Chrome/Firefox on your iPhone, I think it should work as expected.

**Comment by JKesslerPhD** [comment]
@freezecode The problem should now be fixed.  I have also fixed another iOS issue associated with being able to edit log entries on the "View Log" page.  Thanks for flagging this problem, and let me know if you find any others
