### ISSUE TITLE
Altering existing injection record fails with `Date Format Invalid`

### ISSUE THREAD

**Issue by turnipgetsbetter** [JKesslerPhD/FIPInjectionLogger#48]
Steps to reproduce: 
1. Log in to fiplog.com
2. Select `View Treatment Log` > click on the "edit" icon (pencil in a square) on the right hand side of an injection record
3. Alter data (in my case, text was in the "Injection Notes" section of the popup)
4. Click `Save Changes` --> Fails with: `Invalid Date Format Entered` error message in red box at the top of the page 

(The redirection happened too quickly for me to catch the error in the console)

**Comment by turnipgetsbetter** [comment]
@dev team - thank you so much for this incredibly helpful tool. I'm happy to try to dive into some debugging if you point me in the right direction

**Comment by JKesslerPhD** [comment]
> @ devteam - thank you so much for this incredibly helpful tool. I'm happy to try to dive into some debugging if you point me in the right direction

Thanks!  Please post issues as you notice them.  I will try to fix them as soon as I can.  Right now I'm on vacation with limited internet until august, so fixes will unfortunately be a little slow right now.

**Comment by JKesslerPhD** [comment]
I've gone ahead and fixed this error.  It was an error that cropped up when I updated how time is being recorded a few months back.  Logs should not be able to be updated.  Sorry for the delay.
