### ISSUE TITLE
There is no way to indicate that no injection was given on a particular day

### ISSUE THREAD

**Issue by CathyLovesTurtles** [JKesslerPhD/FIPInjectionLogger#49]
Despite spending 4 hours elapsed time and using several needles, I was unable to give my cat his injection yesterday (July 18, 2021).   He kept jerking his body so the needle slipped out.      This morning (July 19, 2021) I took him to our vet where a vet tech was able to do it.   So, I missed Day 47 really.  (This has actually happened at least once before, but I didn't have time to open this ticket then.)   I'm not sure how this should be handled.  Does it mean I have to give injections for two extra days beyond the 84 days?   Anyway, I was wondering if anyone else had suggested this.  Thanks!

**Comment by JKesslerPhD** [comment]
Hi Cathy,

I am not a vet, nor affiliated with any of the FIP-related facebook groups, so cannot provide advice on this topic.  Dr. Pedersen, the veterinary researcher at UC Davis who first published on the efficacy of treating FIP using GS-441524 remains a set of questions and answers on his website: http://sockfip.org/miscellaneous-questions-and-answers-regarding-fip-2020/

Here is what Dr. Pedersen says:

> Q: I have been told that if the kitty misses 1-day dosage the next dosage has to be doubled to cover the previous dosage?
> A: No. Missing one dosage is not serious, because effective blood levels are sustained over 24 h. However, missing a dose is something that should be avoided if all possible as it can become a habit.
