### ISSUE TITLE
Day #x of treatment is different than my calculation

### ISSUE THREAD

**Issue by CathyLovesTurtles** [JKesslerPhD/FIPInjectionLogger#50]
First of all, I love this tool.  Thank you so much!   By my calculation, I am on day #55 of treatment (we started on June 2, 2021), but the program says day #54 today (July 25, 2021).     

Also, would it be possible to add another column to the Treatment Log to indicate which day of treatment is associated with a particular entry.   

Thanks again,  Cathy Ory  (cat is Kiko 💗)

**Comment by JKesslerPhD** [comment]
Hi Cathy,

I've gone ahead and added a day label under the injection log.  Previously that was available if you clicked on the day.  As far as the day you're on -- I think the program is doing the math correctly:

There's 30 days in June, you started on the 2nd -- so 29 days of injection
When you sent this it was June 25 -- so 25 days of injections.

29 (June) + 25 (July) = 54

Let me know if you see other problems or think something needs to be fixed.  I definitely don't know all the errors that occur or why.  I hope your cat continues to do well!  The process is definitely not an easy one.

**Comment by CathyLovesTurtles** [comment]
Hi Jeff,
You are right.  I had made a mistake in writing down the FIP day in my
planner.     Thank you for adding the Day label.
(I still think there should be a way of logging NO INJECTION for a
particular day though - I was unable to give Kiko his injections on three
of the days - so far, and it would be great to see that information
reflected in the treatment log).
Thank  you again for providing this great tool.  Stay safe.
Cathy

**Comment by JKesslerPhD** [comment]
Hi Cathy,

You raise a really good point.  I'll add some functionality in a couple
weeks to allow for a skipped injection to be recorded.

In the meantime, you can create this effect by recording an injection, and
then modifying the log and changing the injection amount to 0 mL.

There were previously some issues with modifying the log, but those issues
have been fixed, I believe.
